
import { Model3D } from './types';

export const MODELS: Model3D[] = [
  {
    id: '1',
    name: 'רונין סייברפאנק',
    category: 'דמויות',
    price: 165.00,
    originalPrice: 220.00,
    rating: 4.9,
    reviewsCount: 128,
    imageUrl: 'https://picsum.photos/seed/cyber1/800/600',
    description: 'דמות סייברפאנק מפורטת במיוחד. כולל גרסה מיוחדת מותאמת להדפסת שרף (Resin).',
    fileFormat: ['FBX', 'STL', 'OBJ'],
    vertices: '120k',
    isOnSale: true,
    isPrintReady: true,
    recommendedMaterial: 'שרף (Resin) / Tough SLA'
  },
  {
    id: '10',
    name: 'מערכת ארגונית למגירות (DIY)',
    category: 'DIY',
    price: 55.00,
    originalPrice: 75.00,
    rating: 4.9,
    reviewsCount: 156,
    imageUrl: 'https://picsum.photos/seed/diy1/800/600',
    description: 'סט מודולרי להדפסה עצמית של חוצצים למגירות. ניתן להתאמה לכל גודל מגירה.',
    fileFormat: ['STL', 'STEP'],
    vertices: '5k',
    isOnSale: true,
    isPrintReady: true,
    recommendedMaterial: 'PLA / PETG'
  },
  {
    id: '7',
    name: 'מנורת שבעת הקנים מודרנית',
    category: 'יודאיקה',
    price: 195.00,
    originalPrice: 250.00,
    rating: 5.0,
    reviewsCount: 42,
    imageUrl: 'https://picsum.photos/seed/menorah1/800/600',
    description: 'עיצוב גאומטרי מודרני למנורה. אופטימלי להדפסה בחומרים דמויי מתכת או פליז.',
    fileFormat: ['STL', 'OBJ'],
    vertices: '85k',
    isOnSale: true,
    isPrintReady: true,
    recommendedMaterial: 'PLA מטאלי / נחושת'
  },
  {
    id: '11',
    name: 'תופסן כבלים שולחני',
    category: 'DIY',
    price: 15.00,
    rating: 4.7,
    reviewsCount: 312,
    imageUrl: 'https://picsum.photos/seed/diy2/800/600',
    description: 'פתרון פשוט ואלגנטי לניהול כבלים על שולחן העבודה. הדפסה מהירה ללא תמיכות.',
    fileFormat: ['STL'],
    vertices: '1k',
    isOnSale: false,
    isPrintReady: true,
    recommendedMaterial: 'TPU (גמיש) או PLA'
  },
  {
    id: '8',
    name: 'בית מזוזה "שדי" מינימליסטי',
    category: 'יודאיקה',
    price: 40.00,
    rating: 4.8,
    reviewsCount: 89,
    imageUrl: 'https://picsum.photos/seed/mezuzah1/800/600',
    description: 'בית מזוזה מעוצב בקווים נקיים. כולל חריץ פנימי מותאם לקלף סטנדרטי.',
    fileFormat: ['STL', 'STEP'],
    vertices: '12k',
    isOnSale: false,
    isPrintReady: true,
    recommendedMaterial: 'PETG לבן / שרף שקוף'
  },
  {
    id: '5',
    name: 'מארז ארגזי מד"ב',
    category: 'אביזרים',
    price: 45.00,
    originalPrice: 70.00,
    rating: 4.8,
    reviewsCount: 215,
    imageUrl: 'https://picsum.photos/seed/props1/800/600',
    description: '10 וריאציות של ארגזי מדע בדיוני. גאומטריה פשוטה שהופכת אותם למושלמים למתחילים בהדפסה.',
    fileFormat: ['FBX', 'STL'],
    vertices: '2k',
    isOnSale: true,
    isPrintReady: true,
    recommendedMaterial: 'כל סוג של PLA'
  },
  {
    id: '12',
    name: 'מתלה אוזניות אוניברסלי',
    category: 'DIY',
    price: 25.00,
    originalPrice: 35.00,
    rating: 4.6,
    reviewsCount: 94,
    imageUrl: 'https://picsum.photos/seed/diy3/800/600',
    description: 'מתלה חזק המתחבר לצד השולחן. כולל ברגים להדפסה לחיזוק מקסימלי.',
    fileFormat: ['STL', 'OBJ'],
    vertices: '8k',
    isOnSale: true,
    isPrintReady: true,
    recommendedMaterial: 'PETG לחוזק מכני'
  },
  {
    id: '9',
    name: 'גביע קידוש מגולף',
    category: 'יודאיקה',
    price: 120.00,
    rating: 4.7,
    reviewsCount: 15,
    imageUrl: 'https://picsum.photos/seed/cup1/800/600',
    description: 'גביע קידוש עם עיטורים מורכבים. דורש רזולוציית הדפסה גבוהה מאוד.',
    fileFormat: ['STL'],
    vertices: '300k',
    isOnSale: false,
    isPrintReady: true,
    recommendedMaterial: 'שרף (Resin) איכותי'
  },
  {
    id: '6',
    name: 'נפח סגנוני',
    category: 'דמויות',
    price: 125.00,
    rating: 4.9,
    reviewsCount: 67,
    imageUrl: 'https://picsum.photos/seed/char2/800/600',
    description: 'דמות נפח מקסימה למשחקי פנטזיה. מודל אטום (Watertight) מוכן לפריסה להדפסה.',
    fileFormat: ['FBX', 'STL', 'Blend'],
    vertices: '25k',
    isOnSale: false,
    isPrintReady: true,
    recommendedMaterial: 'שרף (Resin)'
  }
];
